### ISSUE TITLE
Servo Hat

### ISSUE THREAD

**Issue by TechplexEngineer** [tejashah88/vex4pi#1]
Greetings, Thanks for this great library!

What servo hats have you tested the code with?

Have you tested it with https://www.adafruit.com/product/2327

Thanks!

**Comment by tejashah88** [comment]
Hi @TechplexEngineer,

I did use that exact HAT for testing the code. I'll probably add a section to show which HATs are supported.

Thanks!

**Comment by TechplexEngineer** [comment]
Fantastic! Thanks.
